# ========================================
# Windows 5.8 System Info Starship Prompt
# ========================================

format = """
[â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ ðŸ–¥ï¸ WINDOWS 5.8 SYSTEM](white)
[â”‚ DIR: $directory](white)
[â”‚ DEVICES: ðŸ’¾ A:\\\\ READY   ðŸ“µ DIAL-UP. . . CONNECTED](white)
[â”‚ HELPERS: ðŸ“Ž Clippy ENABLED   ðŸ›¡ï¸ Norton 1337 Threats](white)
[â””>](white) $character"""

add_newline = true

# ========== Directory ==========
# The directory module shows the path to your current directory,
# truncated to three parent folders. The directory will also be
# truncated to the root of the git repo you're currently in.

[directory]
format = "[ðŸ“ $path](white)"
truncation_length = 3

# ========== Character ==========
# The character module shows a character (usually an arrow) beside
# where the text is entered in your terminal.
# 
# The character will tell you whether the last command was successful
# or not. It can do this in two ways:
# 
# - changing colors (red / green)
# - changing shape (> / X)

[character]
success_symbol = "[C:\\\\>â–ˆ](white)"
error_symbol = "[C:\\!!>â–ˆ](white)"
vicmd_symbol = "[C:\\\\>â–ˆ](white)"